import React from 'react';
import { Wrapper } from './styles';

export const FallOfAdam = () => {
    return (
        <Wrapper>
            <h4>The fall of Adam and third evolution of God</h4>
            <p>Innoxus: Dear Master, please explain to me what is meant by the fall of Adam. Is knowledge a sin?</p>
            <p>Ingenito; One of the most controversial questions that have been tormenting the theologians of Christianity and Judaism for ages. </p>
            <p>First, let us do deep into the pre fall state of Adam.  Always keep in mind that Adam is the representative of the human being. Whether Adam lived or not in history is not the question here. There is no history of civilization but evolution of the civilization of mankind. This evolution started from one point. That point is Adam. </p>
            <p>Before the fall, Adam lived by his essence like a child. Jesus said; allow the children to come unto me, because the Kingdom of God belongs to them.  Adam was not conscious of his existence – food, clothing or house.  In other words, the Garden of Eden was a Kingdom of God.</p>
            <p>Then he ate the forbidden fruit from the tree of knowledge. Suddenly he was conscious of his existence. He became conscious of his body and felt uneasy over his nakedness. He covered his body, the naval part of his body with leaves. This is an important point in the evolution of man and civilization. This point is the birth of ethics - what is good and what is bad. We shall say that mind was born. Adam declared unto himself like Descartes’ I think, therefore I exist’. An entirely new dimension in the life of Adam happened here.  Adam was the first judge against sex.  Hence he concealed his naval part first.</p>
            <p>From that point onwards, the development of human civilization is characterized by the eternal clash between <b>essence and existence</b>.  This clash is manifested through the Hegelian triad of Thesis,- Anti thesis and Synthesis.</p>
            <p>Innoxus; Dear Master, when Adam was conscious of his existence, what happened to his essence? Was he bereft of his essence or was it with him? </p>
            <p>Ingenito; Godliness is the essence of every man including Adam. Godliness is love in one self and love in God. It is the image of God. You are born with your essence and you cannot strip it off. The child is an example. It is full of love. It has total faith in the mother. Similarly, if you are rooted in your essence, you love yourself and others. Moreover, you will have faith in the God, a loving God. You are not alone but part of the world. There is a sense of inclusiveness. But once you are conscious of your existence, the focus shifted to material needs.</p>
            <p>First you think of the material needs of the body – food, clothing, and housing. If Adam stops with that there is little harm. The concern for material needs starts grow bigger and bigger. Man becomes concerned about his family. Now he starts acquiring more wealth to ensure the material needs for the future of the family members. When everybody in a community starts thinking on this line, there are islands of families controlling a portion of resources of the earth. This is the genesis of capitalism. Existence is now transformed into Thesis, a system focusing on materialism, leading to socio economic and political inequalities. There emerges a powerful ruling class that controls much of the land and means of production. The vast majority is left outside the mainstream. This is the climax of Thesis. The Essence in man, the godliness or love resists such injustice. This resistance becomes the Anti thesis. At certain point of time, God spearheads the Anti thesis through an incarnation. Then the inevitable clash between Thesis and Anti thesis results in the collapse of the Thesis and a new Synthesis is born. This is the process of the progress of the civilization which includes the social, economic and political systems created by man. To put it in simple Marxian terms it is a constant struggle to control the land and means of production by one section and a counter force to de control the ownership. </p>
            <p>Innoxus; In the clash between Thesis and Anti thesis, why not Anti thesis emerges victorious, why Synthesis emerges? </p>
            <p>Ingenito; This is baffling the philosophers, social scientists and historians. To me it is the mystery of the evolution of God. When Thesis collapses, it incorporates certain elements of Thesis and certain elements of Anti thesis to form Synthesis.</p>
            <p>Innoxus; Dear Master, shall you enlighten me with an example from history about this process?</p>
            <p>Ingenito; We shall analyze the rise and fall of Roman Empire, the fourth evolution of God here.  It is a classical example of the most cruel and inhuman form of Capitalism in the ancient history. The system of slavery was institutionalized with the sanction of the State, the Roman Empire. Except the Roman citizens, the slaves – they are also human beings – were treated like animals. They were forced to work as unpaid laborers in the farms of the Roman citizens, particularly the rich and the powerful.  The strong able bodied youth were singled out and imparted heavy training in martial arts. The Romans used to conduct cruel game festival as an entertainment in large stadiums. The slaves or gladiators would be forced to fight against each other in the games with weapons.  The winner would get freedom and the loser death. </p>
            <p>These gladiators or slaves lived together in large halls. They ate together, slept together. They had only one identity, the slaves. There was so much affection and love between them. All of a sudden, they were forced to fight against each other like mad dogs. They would fight fiercely to protect their lives. The friend of yesterday was suddenly turned into a Satan. The crowd, they were also human beings roared and enjoyed this inhuman fight. A brother was  killing his own brother like a mad dog. </p>
            <p>The vast resources of Africa, Middle East and Europe were under the control of the small number of Roman citizens who constitute the Roman Empire. The sons of the soil – the natives of these countries had no control over their land. They were alienated from their own land by the Roman Army and Roman Laws. This is the climax of the Thesis. </p>
            <p>Now Jesus emerged with his Kingdom of God gospel. This is the Anti thesis, the gospel of love. The Divine Intelligence or the Holy Ghost rebelled against the Roman Empire through Jesus. Ultimately the Roman Empire collapsed and the Christian Empire emerged as Synthesis. Normally, the Kingdom of God would have dawned on earth. What happened? The Christian Empire is a mixture of Roman Empire and the Kingdom of God. Soon corruption set in and the Christian Empire turned into a Thesis – Feudalism emerged. We shall see the details of this process in the fourth evolution of God.</p>
        </Wrapper>
    )
}
