import React from 'react';
import { Wrapper } from './styles';

export const IAndThou = () => {
    return (
        <Wrapper>
            <h4>I and Thou - the experience of Love or God. </h4>
            <p>Innoxus; Dear beloved Master, tell me honestly how to experience God in me? Is there any scientific method or shall I use my reason and experience God?</p>
            <p>Ingenito; Dear Innoxus, the first question reveals your innocence and spark of intelligence. The next question reveals your innocence. However, I am obliged to answer both since you are my trusted disciple.</p>
            <p>To experience God, first you must have an understanding of God. What is God or Being? This understanding leads to experiencing God. The Being or God is the ultimate measure of itself, no measure beyond it. Love, Cosmic Energy and Divine Intelligence constitute the essence of God. You shall call them the trinity of God. These trinities are present in all the creations, be it Universe or life forms in the earth. They are present in you also. If you shall identify them in you, then only you shall experience God.</p>
            <p>Now the question is how or at what level this experience happens.</p>
            <p>Let me ask you a series of questions and please give me your honest answers. Then only you shall experience God.</p>
            <p>Let me start with the trinity of man. What is a human being? What constitutes a human being or what qualifies a two legged animal to call itself a human being.</p>
            <p>Every individual has three parts which I call trinities. First body. </p>
            <p>Tell me Innoxus, who are you? Are you the body? If you lose your right hand, will you say that you are Innoxus without right hand or still you are Innoxus? When you were born with 3 kg body, you were also the same Innoxus as you are now at 60 years of age with 70 kg body. What does it mean? You are not the body but the body belongs to you. Let us go further deeply. What is your birthday?</p>
            <p>Innoxus; 15/10/1944</p>
            <p>Ingenito; Can you remember where were you in January, 1944? That is nine months before your birth.</p>
            <p>Innoxus; I do not remember.</p>
            <p>Ingenito; You are exactly right. You do not remember but you existed then. Half of you was floating in the fluid inside the testicles of your father in the form of a cell or gene. There were billions of your brothers and sisters floating along with you. When this half entered into the womb of your mother, met the ovarian seed of your mother or your other half, Innoxus was medically born. You do not remember that. But it is certain that you are not the body but it is your body. May I take the liberty and say that you are independent of your body?</p>
            <p>Have you ever pondered where you are inside your body, say liver, heart, brain etc? The truth is that you are nowhere in your body but you are everywhere.</p>
            <p>Innoxus; My dear Master, how is it possible to know that I exist without the mind?  I can realize my existence without my hands but not without my mind. Is it wrong if I say that I exist in my mind? I think, therefore I exist.</p>
            <p>Ingenito; Do not quote others. It is dangerous to live under the shadow of other people. Leave Descartes. Go deep down unto yourself and find the truth. Mind is the product of socio - cultural conditioning of a specific period. If mind exists in the brain, then where it does exist. Brain, biologically speaking, is a bundle of flesh made up of genes. Genetic science has proved very convincingly that certain proteins in the genes carry memories of previous generations and play a determining role in the formation of your body and mind - the color of the skin, eyes, certain behavior patterns etc. Modern psychology talks about three level of consciousness that influence your thinking process and behavior. What is mind but the combination of the three? Is it not your mind?  I have my own mind.</p>
            <p>I will ask another question. I give you an orange. Now what will you say. “ I have an orange or I am orange?’</p>
            <p>Innoxus; I have an orange</p>
            <p>Ingenito; The same is the case with mind. When you have a mind, then you are not the mind. My dear Innoxus, do you not exist when the mind ceases to be. What happens when you lapse into deep slumber without dreams? Does it not resemble death? Morning you awake to say good morning. Do you not exist without mind for a few hours?</p>
            <p>The real ‘YOU’ is not mind. YOU exist independent of mind except that you are conscious of mind only when you are awake</p>
            <p> Similarly, if you have a mind, then you are not the mind. This realization will take to another step, very close to the door of experiencing God. Hindu religion calls it Siddha Samadhi and Bhava Samadhi. Siddha means mind and Bhava means emotions.  Your brain has two parts – left side and right side. The right side is the seat of logic, science, the faculty of reason etc. The right side is the seat of emotions like love, anger, mysticism etc.  Mind is the combination of both. (The scientists are still in the dark to understand fully what mind is) Now Samadhi is sepulcher. You should bury your mind along with your emotions in the sepulcher. Now you rise to the third level – the level of no- mind. What Isaiah says “search God in the stillness of the mind” may be this. When the mind becomes still, there is no – mind.</p>
            <p>Innoxus; How shall I rise to the level of no – mind?</p>
            <p>Ingenito; Hindu sages have developed a technique called Dhyana. First you should find a teacher who will train you in Siddha Samadhi and Bhava Samadhi and no – mind. This no – mind is the seat of Divine Intelligence or Holy Spirit and God. Mysticism is the experience of this no – mind. Osho insists on No – mind throughout his discourses.  He calls it dynamic sleep. You are totally asleep and totally conscious of your existence. It is deep silence and bliss. You can experience light and God at this level. </p>
            <p>Now let us discuss the’ I and Thou’ concept. It is Martin Buber, the Hassidic mystic who preached ‘I and Thou’ concept. It is not a concept, rather it is Truth.</p>
            <p>There are three levels of’ I and Thou’ experience. The first level is what Jesus sais” I am in my father and the Father is in me”.  Experiencing the God in man is the first experience of God. He announces the Kingdom of God in the name of the Father.  When he was in agony prior to crucifixion, he prayed to God thus” Father it is not my will but thy will let this chalice go”. He was totally in union with God throughout his mission. “I am going to my Father who sent me”.</p>
            <p>Innoxus; Dear Master, Is it the same as the image of God?</p>
            <p>Ingenito; Exactly the same as I understand it.  The image of God contains the trinity of God; the Cosmic Energy, Love and Intelligence. When you are conscious of this in you, then you have the first ‘I and Thou’ experience. We come across a passage in John; 13 in the gospel. When Pharisees questioned the Son of God status of Jesus, he retorted back with “You are also the gods. Is it not written in the scriptures?”</p>
            <p>Innoxus; Dear Master, please bear with me for interruption. Is this I and Thou experience unique only to Jesus? Is there any mention of this experience in other religions?</p>
            <p>Ingenito; Dear friend, I appreciate your boldness. The Christians will shudder to think in this angle. This experience is the birth right of humanity. The child is born with this relationship but it is not conscious of it. That is why Jesus said “Unless you become a child, you cannot enter into the Kingdom of God” . when his disciples blocked a child from reaching Jesus, he rebuked his disciples and asked them to allow the child to him with the following words” The Kingdom of god belongs to them”</p>
            <p>Many religions have mentioned about this relationship. In Tamil religious literature, you shall find Siddhas, the sages, say, ‘These people search God in many places except in themselves”. In the holy book of Vedas, the relationship of Paramatma and Jeevatma is mentioned. It refers to the first relationship between the I and Thou.  Adam had this experience before his fall. He had direct communication with god in the Garden of Eden. He had the heart of a child then. When mind came into being, this first relationship was cut off. That is his fall or the fall of mankind. The child has no mind and hence it is born with this relationship.</p>
            <p>Now let us discuss the second relationship of ‘I and Thou’</p>
            <p>When asked which of the Ten Commandment is the best, Jesus replied that the second commandment is the best as it is inclusive of all the other commandments. Hence it is called the Golden Commandment. Do you what is it?</p>
            <p>Innoxus; Yes I know; Love thy neighbor as thou love thyself”</p>
            <p>Ingenito; You cannot have the second experience of I and Thou unless you have the first experience. Jesus says the parable of Good Samaritan who is your neighbor. Once you love your neighbor, you become the neighbor and you will do what he has done. He emphasized this second relationship of ‘I and Thou’ when his disciples asked him who would qualify to enter into the Kingdom of God. To this Jesus replied; many people from East and West will flock the gates of Heaven but it will be closed to them. They will shout” God, Have we not prayed in your name and performed miracles in your name. Why have you shut the door? To this I will reply” I was hungry and you fed me not; I was without dress and you clothed me not; I was sick and you attended me not; I was in jail and you visited me not” They will then reply;</p>
            <p> “Oh! Lord when you were hungry, when you were without dress, when you were sick and when you were in jail?”</p>
            <p>I will tell them” Have you not seen the poor without clothes, hungry, sick and in jail? They are but me”</p>
            <p>This is the second relationship of “I and Thou”. When you experience the God in you, then you realize that the same God exists in Thou, your brethren. At this level, I and Thou are one and the same. Then only you shall pray authentically’ Our Father thou art in Heaven’ </p>
            <p>Innoxus; Dear Master, you said that the second relationship is not possible without the first relationship. That is first one must have the ‘I and Thou’ relationship with God. Then only one must develop the second ‘ I and Thou’ relationship with the neighbor. But the great EVR and Karl Marx had profound love for the poorest of the poor. But they never believed in God.  Do you mean to say that they did not have the second ‘I and Thou’ relationship?</p>
            <p>Ingenito; Dear man, you ask a lot of wonderful thought provoking questions now. EVR, Karl Marx or all other atheists rejected the personal god or the alter ego of the religions. This God is the projection of the mind and not the truth. But God as Truth does not belong to religion. I am absolutely certain that the hearts of Karl Marx and EVR were filled with love. Where there is love there is God. So EVR and Karl Marx had the first experience of God in themselves through love. They are highly religious people not men of religion. Love flowed from their hearts towards their poor brothers and sisters. In other words, they had the ‘I and Thou’ relationship of God and the’ I and Thou’ relationship of neighbor. </p>
            <p>Now the third relationship. ‘I and Thou’ relationship with Nature.</p>
            <p>In the Book of Genesis it is written that God reveals in Nature, Time, Space and History. In The Baghavad Gita, The Holy Song of the Hindus, Lord Krishna declares that He is in the trees, fruits, flowers, water, fire, universe and in everything created. God in Nature idea is found in all major religions and religious groups all over the world.</p>
            <p>Innoxus; Dear Master, is it not then Pantheism?</p>
            <p>Ingenito; Yes, Pantheism is the pure form of religion. The early Greek philosophers considered animated Nature – Hylozoism - the Ultimate Truth. The tribal communities all over the world still maintain this faith as part of their religion. If you love Nature, it will protect and nourish you. Take the example of the devastating Tsunami. It is the civilized human beings who suffered the human casualties. When the Tsunami devastated Andaman Islands, not one human casualty was recorded among the tribal community. They understood the language of Nature and escaped. The animals and birds became restive and ran towards the higher areas of the hill just before the outbreak of Tsunami in the sea. Realizing a catastrophe, all the tribal families living in the low areas immediately joined the exodus of the animals, birds and reached the higher areas for safety. What do you understand from this? Nature is so concerned about you and protects you if you develop the ‘I and Thou’ relationship with Nature.</p>
            <p>Mother Nature is so pure that it provides pure air, pure water and herbal plants to cure your illness. The modern civilized world has to learn a lot from the tribal medicines.</p>
            <p>The tribal judiciary is also Nature oriented. The tribal community does not have the Penal Code like the civilized modern communities like us. When an individual violates the tribal law or community ethics, he is ex communicated from the community. He is cut off from the ‘I and Thou’ relationship with the community. He is condemned to live all alone with Nature. This social exclusion provides him an opportunity to reflect and repent. He realizes his sin and returns back to confess his sins to the tribal chief and ask for pardon. The tribal chief forgives his sins and the sinner is integrated into the community.</p>
            <p>Ingenito; </p>
            <p>Innoxus; Master, bear with me for a last question. Shall I assume that what you have been describing above is also the experience of God by Jesus?</p>
            <p>Ingenito; I am not qualified enough to say anything about the experience of God by Jesus. Have you not read that Jesus spent forty days in the wilderness and prayed without food? When he completed the prayer, it was written that angels nursed him. He had the experience of God then. We come across similar experience situation in the life of Prophet Mohamed. He also spent forty days in a cave in Arabia. Finally, Angel Jibriel (Gabriel) appeared before him and taught Holy Quran to him.  The Hindu Sages and Rishis have spent years in mountains or caves to get enlightenment and experience of God.</p>
            <p>I will be able to say anything on the experience of such great men only after I get such mystic experience. What I have been describing above is to help you get an understanding of the experience of God and not the real experience.</p>
        </Wrapper>
    )
}