import React from 'react';
import { Wrapper } from './styles';

export const KingdomOfGod = () => {
    return (
        <Wrapper>
            <h4>Kingdom of God</h4>
            <p>Innoxus; Dear Master and the Enlightened One, throw some lights on ‘The Kingdom of God? Does it refer to a place or a mere concept?</p>
            <p>Ingenito; My dear disciple, you have never asked a question that has relevance and appropriates to the 21st century. Thank You for your innocence.</p>
            <p>Kingdom of God starts with man or it should start with you. Jesus said” Kingdom of God is in you”. It is not somewhere out in the space. It is a condition of the mind.  To begin with, it is a state of mind. Jesus insists on following the golden command – the second command of the Ten Commandments – as a pre condition to enter into the Kingdom of God. It is; “Love thy neighbor as you love thyself”. The commandment has two parts. First, Love thyself. Now why should you love yourself?. In the Book of Genesis, we come across the saying that man was created in the image of God. What is the image? The essence of God is Love. Hence the essence of man is also love. When you are conscious of the love deeply rooted in your heart, you shall declare that God is in you. This is how I interpret the saying of the Christ in St. John; verse 13. When Pharisees questioned how Jesus could claim that he is the Son of God, Jesus replied” You are also Gods, is it not written in the Scriptures”.  When you realize love in you, you cannot but love yourself because you are the image of God. </p>
            <p>Innoxus; Dear Master, when you say love yourself, does it mean that one should love his body?</p>
            <p>Ingenito; Really a wonderful doubt.  St. Paul in his Epistle to Corinthians declares thus” Your body is the temple of the God”. When your heart is filled with love, then it is the seat of God. It is then a spiritual imperative to love your body.</p>
            <p>Innoxus; Dear master, is it not the same as the Paramatma and Jeevatma relationship we come across the Hindu religious scriptures?</p>
            <p>Ingenito; Exactly the same. The essence of man – Jeevatma is identified with God, the Paramatma. In other words, the Creator is one with the creation.  We shall return to the Kingdom of God.  Love of the body refers to the basic physical and mental requirements. In the Lord’s prayer we come across only one request” give us our daily bread”. The body requires food for nourishment. That is the basic and fundamental need. We must develop the culture of enough. Anything beyond is capitalism and in the Kingdom of God, there is no room for capitalistic thinking “not enough”.</p>
            <p>Now we shall see the second part of the golden commandment.  <b>Love thy neighbor</b> as you love thyself. A teacher of Law asked “who is my neighbour?”  and Jesus gave answer through a beautiful parable. “There was a man going down from Jerusalem to Jericho and he fell into the hands of the robbers. They stripped him, beat him and went off leaving him half dead. It happened a priest was going along that road and saw the man, but passed by on the other side.</p>
            <p>Likewise, a Levite saw the man and passed by on the other side.  But a Samaritan too, was going that way, and when he came upon the man, he was moved with compassion. He went over him and treated his wounds with oil and wine and wrapped them with bandages. Then he put him on his mount and brought him to an inn where he took care of him. The next day he had to set off, but he gave two silver coins to the inn keeper and told him; ‘Take care of him and whatever you spend on him, I will repay when I come back’ The Jesus asked” Which of these three, do you think, made himself neighbour to the man who fell into the hands of the robbers?” The teacher of the Law answered” The one who had mercy on him” And Jesus said” Go then and do the same”. When you love thy neighbour, you become the neighbour. You will do what he does. The neighbour does help others in utter need out of love. You also help others out of love. Then you enter into the kingdom of God.</p>
            <p>When the disciples asked Jesus who would qualify to enter into Kingdom of God, Jesus replied thus; “People from east and west will throng at the gate of heaven. They will shout “Oh, Lord. We prayed in the temples in your name, we performed miracles in your name. But I will tell them; ‘ I was hungry and you fed me not, I was without clothes and you clothed me not, I was sick and you attended me not, I was in jail and you visited me not’ They will ask, Lord when you were hungry, when you were without dress, when you were in jail and when you were sick? I will reply; Have you not seen the poor who were hungry, sick, without dress and in jail. They are me” </p>
            <p>Jesus then says emphatically that those who gave food for those who were hungry gave clothes to those who were without dress, attended on the sick and visited the poor in jail are eligible to enter into the Kingdom of God. The world will become Kingdom of God if everybody gets their basic needs out of love. </p>
            <p>In the Kingdom of God, everybody lives like a child. The child has no anxiety for future. It is not concerned about amassing wealth and money for future. Again Jesus said; look at the birds, they never sow, nor reap and store food in the barns; God provides them their food. This is the mindset of the child. It has faith in the mother that she will feed her. The child only loves. If we develop such a mindset where essence and existence are in full harmony, we shall create Kingdom of God in this earth.</p>
            <p>Innoxus;  Dear Master, does not communism or socialism also stress on the basic needs to all, say food, shelter, medical support and political justice? Is communism and Kingdom of God is the same? </p>
            <p>Ingenito; At the functional level, there are similarities. But communism or socialism believes in perfect equality. Everybody is equal before law. There is no rich and the poor. Everybody is legally entitled to get their basic needs and justice. There is a political structure and legal system to ensure this equality. But the Kingdom of god is not a social or political system. Love is the only constitution in the kingdom of God. It is a large community of people filled with love because we are the children of the loving father. The hunger of my brother is my hunger; the illness of my sister is my illness. We have equal rights over the resources of the earth as it belongs to our father in heaven.  The earth has adequate resources to meet the needs of everybody but not the greed. Greed is the child of capitalism because greed accumulates wealth and it is person centric not community centric. So there is no place for capitalism in the Kingdom of God.  That is why Jesus began the Lord’s Prayer with; ‘Our father in heaven; let thy kingdom come’. There is a moral responsibility for every member in the Kingdom of God to utilize the resources of the earth to meet the basic needs. There is no question of taking ownership of the resources of the earth and over exploitation of its resources. There is no room for global warming and destruction of biodiversity as God is revealed in Nature. Destruction of Nature is destruction of God.</p>
            <p>In other words, there exists a perfect harmony between essence and existence in the Kingdom of God.</p>
            <p>The early converts to Christianity (there was no religion as Christianity immediately after Jesus Christ) lived in small communes. Love in Christ bound them together. Whatever income they earned was placed before the commune which provided adequate money for each member to look after his/her family. The culture of enough was the economic policy of these communes. Each for all and all for each was the social ethics. Love was the religion they believed in. But the conversion of Emperor Constantine and the emergence of Christian Empire buried Christ and the early Christian communes under foundation of the  Roman Catholic Church.</p>
            <p>Innoxus; Master, is it possible to establish the Kingdom of God in this world. Has any attempt been made after Jesus to experiment this? </p>
            <p>Ingenito;  Before Jesus, say about 500 AD, Pythagoras made a bold attempt to establish a model commune system based on the Kingdom of God, though he was not conscious of the term Kingdom of God. But he met stiff opposition from the capitalist forces and his community was persecuted and his commune was destroyed.</p>
            <p>In the 20th century, two persons attempted create an egalitarian community based on the universal principles of equality to justice and opportunity. First, the Grama Swaraj model of Gandhi.  Gandhi visualized a Utopian social, economic and political model.  Each Panchayat is an independent political and economic unit. The land belongs to the Panchayat which provides everything for the basic needs of the community members, but to their greed. This is the spiritual content of this model. Cottage industries and village crafts define the economic policies of the Grama Swaraj. The political structure is secular in the sense that it accommodates everybody irrespective of caste or religious background.  It is unfortunate that the Indian Constitution buried his Utopian model under the volumes of economic and political policies.</p>
            <p>Innoxus; Dear Master, please bear with me for the intrusion. Do we not have the Panchayat Raj system in working all over India through constitutional amendments?</p>
            <p>Ingenito; The present Panchayat Raj system is only an extension of the Parliamentary and Legislative political systems. We have a three tier system of governance. The Parliamentary system regulates the Union or Central Government, the Legislative system regulates the State Governments and the Panchayat system regulates the villages. The common evil in these three systems is that they are controlled by political parties with the blessing of the big business corporate houses. The Gram Swaraj died through abortion with the birth of the free India.</p>
            <p>Now let us see the other bold experiment. First you must know the person who attempted the model. Innoxus, have you heard of Polpot, the communist chief of Kampuchea, the erstwhile Cambodia? </p>
            <p>Innoxus; Yes, yes, I have heard about him. The cruel military dictator who massacred tens and thousands of innocent people. Am I right? </p>
            <p>Ingenito; No, you are not right.  Your understanding is conditioned by the massive brain washing conducted through media by the western countries, particularly United States. Polpot was a Buddhist monk and a poet by nature. Can you imagine a Buddhist monk and a poet be a cruel man killing tens and thousands of people?  Buddhists are trained to be soft. But a poet has highest level of emotional integrity. Polpot is a mixture of both.  He went to study religion in Sobourne University in France. There he came across two influences. First, the commune system of Marxism of Chairman Mao Tse Tung of China. Second influence is Kibbutz commune of Jews. In both systems, the land and means of productions are under the control of the commune. All the members of the commune are treated as equals. But there is a qualitative difference between the two systems.  In the Chinese commune system, everybody worked in the commune and they got equal wages. They had to look after their families with their earnings.  Since the commune owned all means of production and land, the price of the goods were determined by the commune. The prices of the essential commodities were always within the earnings of the members. However, in the Kibbutz system, the commune takes care of the all needs of the members which include education of the children, medical assistance and even marriage expenses. The community members have no need to save money or acquire wealth for future. Impressed by the plus and minuses of these two systems, Polpot developed an innovative but revolutionary politico economic system based on agriculture. It has many similarities with the Kingdom of God and much dissimilarity.</p>
            <p>First he closed down all the major industries, except arms industry, and the universities. He also dared to abolish currency, particularly dollar. He divided the country into small communes – like the districts in India.  The communes were the real owners of the land and all the means of production. Agriculture, cottage industries and village crafts enjoyed the patronage of the State. All the members of the commune get same dress and same food. They lived in large halls. Individual house ownership – the embryo of Capitalism – was not allowed in the State.  There was community kitchen in each village. The State took over the responsibility of the education and future job of the children of the commune members. But everything was done through gun point because Polpot believed in the doctrine of Justice articulated by his mentor, Chairman Mao. That is Justice is born out of the barrel of the gun.  It was not love that united the commune members as one family. It was fear that united them.</p>
            <p>Do you know what happened to Polpot and his agrarian commune? America was so scared of Polpot. If Cambodia survived even without dollars, then there was a possibility that more and more third world countries might emulate this move. America survives as a world power only through its dollar – the world currency. To say no to dollar means no to America. Hence it was hell bent to destroy Polpot. But it was very difficult task for America to do away with Polpot alone as he enjoyed total support of Mao and the Chinese Army. Now America found the enemy’s enemy – Russia which was also annoyed by the agrarian commune system.  The then Soviet Union considered that only Russia had monopoly over communism. They were equally scared of Polpot and his rival commune system.  At this point, both Russia and America joined hands and instigated Vietnam to wage a war on Cambodia and eliminate Polpot. When Vietnam invaded Cambodia, Mao ordered the Red Army to attack Vietnam. Russia launched a massive border war on China. The Red Army was alarmed at the turn of events. China has a separate constitution for the army. The role of the Red Army is to secure the borders of China against foreign invasion only.  Hence the Red Army Generals revolted against Mao and persuaded him to ditch Polpot. Mao could not but oblige Red Army. Polpot was eventually overthrown by Vietnam and Polpot and his Utopian agrarian commune are now buried in the jungles of Thailand.</p>
            <p>There is one important lesson from history. Capitalism will not allow the emergences of Kingdom of God in this world.</p>
            <p>Innoxus; Master, I have two doubts. Is Kingdom of God is a system of charity? For example, I was hungry and ye fed me etc. Second, is it possible to establish or create a model based on the Kingdom of God in the world now?</p>
            <p>Ingenito; I sincerely appreciate the innocence and insight of your questions, my dear disciple. There are two interpretations regarding the Kingdom of God. One is based on charity. The Church from the beginning to the end of the 20th century focused on this charity approach. There is an inherent contradiction in this approach. Giving food to those in hunger requires two actors – a giver and a receiver or a rich and a poor. There is inequality. There is another interpretation based on the right to life and livelihood. This interpretation seemed to be near to the content of Kingdom of God.  Here the right is not the legal right but the divine right. We are the children of God as He is our beloved Father. Hence we have a divine right to life and livelihood. This right is based on love and not on charity. There is no giving and receiving but only sharing the resources of the earth with love.</p>
            <p>Now your second question. Yes, there is a possibility to establish a Kingdom of God in this earth through the neighborhood communities. The early Christians lived in neighborhood community social system. It is a group of 30 people who are members of the neighborhood. They sit together and discuss their problems, the problems of their families and their locality. They are held together by the love of Jesus. Each member is concerned about the other. They share all their resources among themselves out of love. There is no question of giving and receiving. The money should be common. The need of the individual is the concern of others. The children belong to the community and not to the individuals. There is no question of orphans as the community is the parent. The economic ethics is the ethic of enough.</p>
            <p>Each member promotes one such neighborhood community and the thirty members promote another thirty communities. Once all the members in a Panchayat are mobilized under neighborhood communities with the gospel of love and ethics of enough, they take political control of the Panchayat through election. Now the Panchayat is a mini Kingdom of God as it ensures the basic needs of all the members through its resources. The greed of individual has no place in the Panchayat. In short it is a pure socialistic system.</p>
            <p> If all the Panchayats in India become neighborhood Panchayats, then India will be a Kingdom of God. When this model is replicated throughout the world, then the entire world will be a Garden of Eden or Paradise. There will be no wars, no famine, no poverty and no corruption. Hundreds of billions of dollars now spent on arms industry will be diverted to social securities like education to all, safe drinking water, high quality medical services, housing etc. </p>
            <p>Innoxus; Dear master, it is a wonderful idea. But who will initiate this process?</p>
            <p>Ingenito; Why not you? The whole process should start from an individual with a commitment and willingness to sacrifice his life to the cause because the capitalistic system with its die hard adherents, say politicians and the rich will be all out to destroy such a system from emerging. Hence the initiator or the originator should imbibe his fire and missionary zeal to an army of equally committed volunteers who will spread this new Gospel until the last bastion of the capitalism is wiped out.</p>
        </Wrapper>
    )
}