import React from 'react';
import { Wrapper } from './styles';

export const Soliloquay = () => {
    return (
        <Wrapper>
            <h4>Soliloquy of the Ingenito</h4>
            <p>I crashed through the iron gates of life, bleeding from the torn fleshes and bruises. My heart is aching and a drowsy numbness is paining my senses as if I am drinking the poison of life like the immortal bard Keats. My persistent search to find answer to the fundamental problems of existence is still eluding me as I found myself like a child stranded in a festival ground divorced from its mother. </p>
            <p>What is God, what are the qualities and attributes of the God? </p>
            <p>Evolution of God is an attempt to find out what is Truth or God. Truth is not confined to the corridors of religion or philosophy alone. As the author of Genesis exclaims; “God is revealed in nature, history, space and time” </p>
            <p>Hence an integrated approach is required. It is time to synthesize religion, philosophy, science, and history to find out the Truth. </p>
            <p>Various attempts have been made by great enlightened minds all over the civilized world in the past to find out what Truth is; Dhamma in Taoism, Torah in Judaism, Logos in Greek philosophy and western philosophy, Prakirithi and Purush in Indian philosophy are such examples.</p>
            <p>Evolution of God encompasses everything under the sky to find out Truth.</p>
            <p> do not know whether this approach is right or wrong. I do not claim that I have found out the Truth. This is only a search.</p>
            <p>Science and Technology has been progressing in leap and bounds. It even dares to challenge God and the Creation theory. Two such important discoveries are shaking the very foundation of religion from its foundations. One is the discovery of the so called God’s particle or Higgs Boson particle. The second one is Book of Life that catalogues the gene sequence of all living beings. Coordinator of the research team of Book of life, Dr. Warren Bret has openly challenged God that there is no need for God to create life as he himself shall be able to create life through genes.</p>
            <p>Scientists now proclaim that they have discovered the mystery behind creation in the Cern laboratory. Stephen Hawkins even went to the extent of declaring that the Universe has everything in it and that there is no need for God to create.</p>
            <p>This emerging trend in Science and Technology shall be the impending spiritual catastrophe looming large along the horizon of the human civilization. I have a fear that Science and Technology seems to vindicate the declaration of Frederick Nietzsche that God is dead. That God is dead if taken seriously will breed nihilism in man as he narrows down the distance to his grave yard in his old age.</p>
            <p>The prophecy of Noah Yuval Harare that the great pandemic of the third millennium will be suicide stands a good chance to be a reality.</p>
            <p>Is it true that the kingdom of mind or reason is ultimate and God is but a projection of mind, not a reality? -</p>
            <p>We seek Truth in fragments not in its totality. Knowledge is compartmentalized and dismembered in text books. We get a lot of information in educational institutions. Do we get a glance of Truth in the educational institutions? Then where shall we find Truth? Shall we wait with faith that Life will open its mouth and enlighten our hearts with Truth through our experience? </p>
            <p>Or shall we unite all the branches of knowledge into a single system of thought and search the Truth there? </p>
            <p>Am I qualified enough to claim that I have found God through the highway of the Kingdom of Reason. Shall Reason have a glimpse of a faint ray of God? </p>
            <p>Let me put aside of the search for God for a moment and focus of Life. What is Life? Does life consists of eating, working, having sex, begetting children and die? Is that the meaning of life? If so, do not animals and birds do the same thing? Is there a meaning in life beyond that? </p>
            <p>I know that my days are numbered like all my brethren that are inhaling breath and exhaling it out. But I see chaos and social injustice everywhere. Brother is fighting against brother and sister is fighting against sister to possess as much material as possible from the creation of God – the earth which is as miniscule as a grain of sand against the vast unknown fathomless expanse called Universe. We know very well that possessing wealth in this world in a brief span of time, say 80 to 90 years, is like a forgotten dream while in the death bed. </p>
            <p>The agony of leaving the wealth, the loss of pleasures in life, the permanent separation from the people whom we believed that they loved us and we loved them torment our heart as we gasp for breath in the death bed. We witnessed such a horrible scenario in the lives of our forefathers, our reasoning mind forewarns of its reenactment in our lives also. Still we fight for wealth, involve in fleeting sensual pleasures as an everlasting reality, kill our brothers and rape our sisters in the name of the dirty concept called patriotism.</p>
            <p>But death proves again and again that they are but illusions of life. Then what is the Ultimate Reality. My pleasant and fragrant youth is gone. I am now a withered rose and the distance between my grave yard and my remaining days in this world is getting narrower and narrower with every rotation of the earth which we call day and night. What remains from the illusion of life is panic caused by uncertainty of future after death. Is there a life after death? Answer to this question is still eluding the scientists, philosophers and God men alike. They give only assumptions and dreams which my reasoning mind refuses to accept and rest in peace. </p>
            <p>I rely more on the Kingdom of Mind and as I am walking on the Highway of Reason, I am all alone walking along the valley of spiritual death with the shadow of the Angel of Death constantly hovering over my head with panic gripping my belly. I see my graveyard yonder. Will life cease to be like a bubble and what happens to me after death? Will I dissolve in the Black Hole and get lost in the eternity without any trace or will I go to a new vast planet where honey flows with Yahweh , Jesus, Mary and other saints sitting on thrones and my father, mother and other relatives waiting for me with cheer and everlasting happiness. Oh! What a blessing was the bliss ignorance.</p>
            <p>Is religion an invention of mind to withstand spiritual collapse caused by nihilism and existential frustration? If so well and good. But is not religion the cause for all wars and social injustices caused to mankind? I appease my God through certain rituals and get absolved of my sin. How many persons I have met whose hearts are filled with love for humanity but they do not have religion. Are they sinners? How do they withstand such existential agonies and frustrations?</p>
            <p>Is God then is an experience experienced in the stillness of mind which is the true prayer. How to experience that? Is there any methodology or technique?. Does love require such a methodology or technique to learn and practice?</p>
            <p>Like King Lear, I am crying “ I am more sinned against than sinning”. What caused my sin? Myself and my weak flesh? It is written “ When sin abounds, grace intervenes”. Why did not Grace intervened to save me from my sins – kilos of marijuana, alcohol, tobacco, masturbation, prostitutes, fucking and what not? I feel like crying from the cross “ My God! My God! Why have you forsaken me?</p>
            <p>But my rational mind still refuse to accept a God that cares me like mother with flesh and bones, a God who hears my agonizing cries and saves me.</p>
            <p>Whom shall I find solace by sharing my agonizing and turbulent heart? Innoxus, my other half, you alone shall help me to discover myself.</p>
            <h4>1. The Essence of God</h4>
            <p>The Being or God constitutes the trinity of Energy, Intelligence and Love. This trinity is the essence of the Being or God. Creation is the process of the Becoming of the Being. In this process of Becoming, the Being is in the creation. In other words, the Being  - or I shall call it the Creator-  is not independent of the creation. The Being is not a person but an authentic Truth that is manifested in all forms of the creations – both inorganic and organic.</p>
            <p>In the Book of Genesis, Yahweh reveals itself to Moses in the Mount of Sinai in the following words. “I am THAT I am”.  What is THAT?  It is the ultimate Reality.</p>
            <p>The Hindu religion talks about MAYA which has two syllables; MA means not and YA means THAT. Anything that is not THAT is MAYA or illusion (Illusion is not the appropriate synonym for MAYA but I do not have any other word right now)</p>
            <p>If the mind concludes that the earth with all its bio diversity and systems created by human beings is the ultimate reality, independent of THAT or Being, then it is MAYA. On the other hand, if the Being is perceived in all the creations, the MAYA evaporates like a dew drop from the sunlight.</p>
            <p>In the book of Genesis, the presence of God in the creation is asserted in the following words; “God reveals in history, nature, time and space”. This statement shall be interpreted as that the creator is in the creations. Lord Krishna also reveals his omnipresence in the creations to Arjuna in the following words” I am the universe, fire, water, wind, the trees, the king, the subject, the life and even death” Krishna even goes to the extent of asserting that He is in Arjuna also. </p>
            <p>What then constitutes the essence of God? Quantum Physics asserts with certainty that there exists only one unit of energy in the Universe that is neither created nor can it be destroyed.</p>
            <p>This <b>Inness</b> of the Being in the organic and inorganic forms constitutes the mystery of Becoming.</p>
            <p>First, in the grand design of the inorganic forms in the Universe and then the organic evolution of life forms in this world.</p>
            <p>This evolution is manifested at two levels; first in the eternal conflict in man between his essence and essence. This conflict starts with the fall of Adam, the representative of man. In Adam, the mind came into being or Adam was conscious of his existence. He was the archetype of the Descartes model of existence. “ I think, therefore I exist”.  He is the first inventor of ethics, the good and bad and thereby he gets alienated from his essence. He was in total communion with God before his fall. In other words, he identified himself with his essence, the God in himself.</p>
            <p>The fall of Adam was the starting point of the evolution of civilization which includes religions, political systems, and economic systems. The eternal internal conflict between essence and existence is manifested through the Hegelian triad of thesis, anti thesis and synthesis. This process constitutes the evolution of God. Love and Intelligence fashion the Becoming into a cosmic unity based on cosmic justice. We shall find the evidence of this in the evolution of God in the following chapters.</p>
            <p>We shall find the presence of this trinity in the evolution.</p>
            <h4>2. Birth of the Universe - the first evolution of God.</h4>
            <p>Scientific world is now focused on the search of God and the origin of life in the Universe. Scientific experiments are going on in the western world to find proof for the birth of Universe through a scientific assumption called Big Bang.</p>
            <p>The most popular theory of our universe's origin centers on a cosmic cataclysm unmatched in all of history—the <b>big bang</b>. This theory was born of the observation that other galaxies are moving away from our own at great speed, in all directions, as if they had all been propelled by an ancient explosive force.</p>
            <p>Before the big bang, scientists believe, the entire vastness of the observable universe, including all of its matter and radiation, was compressed into a hot, dense mass just a few millimeters across. This nearly incomprehensible state is theorized to have existed for just a fraction of the first second of time.</p>
            <p>Big bang proponents suggest that some 10 billion to 20 billion years ago, a massive blast allowed all the universe's known matter and energy—even space and time themselves—to spring from some ancient and unknown type of energy.</p>
            <p>The theory maintains that, in the instant—a trillion-trillionth of a second—after the big bang, the universe expanded with incomprehensible speed from its pebble-size origin to astronomical scope. Expansion has apparently continued, but much more slowly, over the ensuing billions of years.</p>
            <p>Scientists can't be sure exactly how the universe evolved after the big bang. Many believe that as time passed and matter cooled, more diverse kinds of atoms began to form, and they eventually condensed into the stars and galaxies of our present universe.</p>
            <p>The big bang theory leaves several major questions unanswered. One is the original cause of the big bang itself. Several answers have been proposed to address this fundamental question, but none has been proven—and even adequately testing them has proven to be a formidable challenge.</p>
            <p>If we take a deep look into the structure of the Universe and the atoms, we are amazed to find the hands of Intelligence and Love in the design and functioning of the universe.</p>
            <p>There are two worlds in the universe. They are seen world and unseen world. Quantum physics agree that there is only one unit of energy that transform into other forms of energy through a process. This single unit of energy is neither created nor can it be destroyed. There is existence of dark energy – 64% which we cannot see. One such example is Black Holes which is mega energy concentrated in a single point. The gravity is such that it shall draw stars bigger than Sun and consume it without leaving any trace. But we cannot see them as we see the planets and stars.</p>
            <p>Now the atoms. Atom is the smallest minute form of matter. The existence of atom defies human eye sight or the most advanced scientific telescope. The existence of atom is proved by the scientists through scientific theories. The existential proof of atom was demonstrated in the destruction of Hiroshima and Nagasaki during the Second World War. Inside the atom there is space in which protons, electrons and neutrons revolve at huge speed. If the atoms are split, it releases immense energy. Two questions still defy any rational answer to the scientific world.. .who or what created the atom. How is it that minute particles, proton, neutron and a host of other particles , found their way into atom? These atoms are the building blocks of the stars, planets and all inorganic matters in the world. Trillions and trillions of atoms form the planets and stars and mountains in the world. There seems to be the hand of an unseen skillful artisan at work behind this phenomenon.</p>
            <p>Now we shall take a look at the solar system. Sun holds all the nine planets and the satellites, say moon, in their fixed orbits through the massive gravitational force of the sun. Let us take a look from the angle of the planets. What holds the Sun as the center of the orbit of the planets? It is the combined force of the gravitation of the all planets. Moreover, each planet holds other planets in their fixed orbits through its gravitational pulls and pressure. Mercury not only holds the Sun at the center of the solar system, bur it has a definite role in keeping the Earth in its orbit and vice versa. In other words, it is all for each and each for all.</p>
            <p> We shall find the presence of the trinity of the Being in the solar system. First it is the unseen energy field that maintains the cosmic harmony. The divine intelligence designs and maintains the planets in their orbits. Above all, it is the Love that creates the condition for each for all and all for each. The life in Earth is possible only through the presence of this trinity of the Being in the evolution of the universe and the solar system.</p>
            <h4>3. Evolution of life forms in the world – the second evolution of God.</h4>
            <p>Religion – mythologies and organized religions – philosophy and science have been attempting to explain the origin of life in this world through their areas of investigation. True philosophy – Sophos – and religion relied on revelation of Truth to explain God and Creation; Science relied on empirical evidence through scientific investigation to find out the origin of life in the world. Let us start with religion and philosophy first.</p>
            <p>Genesis, the first of the five books called Pentateuch, starts with an account of creation of life forms..</p>
            <p>Creation of life forms began with vegetation, followed by sea based living organisms, say fish, then birds which was followed by wild animals. Finally man was created in the image of God. This is the process of evolution. . However, modern science agrees with this process of evolution in many areas except the beginning. </p>
            <p>There has been consensus of opinion among the scientists that the universe and life forms are the outcome of a process called evolution. The geologists studying the rocks and stones for traces of early life forms in the form of fossils or markings have come to a conclusion that early life forms originated in the sea. The Record of Rocks, the reference point of origin of life is estimated to be 1,600 millions of years old. The earliest of the rocks called Azoic rocks contain no traces of life. The first traces of life forms, say fishes, appeared in the Silurian division of Palaeozic Rocks division, about 500 million years ago. The organic evolution are traced from this point. </p>
            <p>What are these life forms consists of. What builds these life forms? Modern science has proved with authentic evidence that cells are the primary building blocks of all life forms. Now they talk of genes which contain DNA structure in helix form. Inside the DNA are found pairs of chromosomes. The mystery of the biodiversity of life forms is now resolved very convincingly. </p>
            <p>The difference in the number of pairs of chromosomes determines the different species. Like species beget the like due to this constant, say fixed number of chromosomes. Lions beget only lions and human beings only human beings. Inside the chromosomes, the scientists have discovered certain proteins that retain genetic memory. This memory spans seven generations. For example, when a child is born, its genes contain certain hereditary traits that include color of the skin, eyes, and even certain diseases. Besides, the intellectual faculty of the fore fathers and certain emotions are stored inside the genes. Four generations of fore fathers may be black complexioned but the child may be white. This is due to the genetic memory of the genes. The fifth generation of the forefather (great, great and great grant father) might be white complexioned. This is the unbroken chain of life.</p>
            <p>The roses may blossom and wither but the rosiness is eternal. Similarly, man may born and die. But human beings exist for ever. In other words, the individual is a link of the chain of life. When he dies, he leaves a part of him through his sons and daughters. He continues to exist.</p>
            <p>Is there any similar thinking in religious scriptures? In the Book of Genesis it is said; God reveals through history, nature, space and time. The omnipresence of the creator in the creations is stressed through these words. But in Baghavad Gita, Lord Krishna declares His Inness in the creations; I am the sky, water, wind fire and all the best elements of nature. Moreover, Arjuna I am in you.</p>
            <p>All matters are the assembly of atoms and each atom is a mini solar system. .Proton and neutron rotate round a nucleus inside the atom.   It should be borne in mind that atom belongs to the unseen world. The gene is a much more complex structure. </p>
            <p>The question is what created the atom and gene. Let us now hear what Einstein says of this. He declared openly that he did not believe in the God of the religion. Though a Jew, he had no faith in Yahweh. But confronted by the mysteries of the universe and cosmic harmony – the immense black energy, expansion of the Universe, the order and discipline of the solar system, the multitude of biodiversity -  he declared in the Solvay Conference of Nobel Laureates that there is a God and the God does not play dice. </p>
            <p>The Inness of the Being in the creation with such order and harmony reflects the unseen hand of the Divine Intelligence or Holy Spirit. The grant design of the universe is designed by the Divine Intelligence.</p>
            <p>The Becoming of the Being is the evolution of creation...</p>
            <p>Am I right? How dare I claim to be right unless it is tested? I have only one way. Let me share my torments and agony with Innoxus, my dear friend and disciple who has the intellectual honesty like a child. </p>
        </Wrapper>
    )
}